# Generated by Django 5.2.7 on 2025-10-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="commennt",
            new_name="comment",
        ),
    ]
