# Generated by Django 5.2.7 on 2025-10-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("emp_id", models.CharField(primary_key=True, serialize=False)),
                ("emp_name", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
            ],
        ),
    ]
