# Generated by Django 5.2.7 on 2025-10-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_id",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
